<span style="font-size:10pt">&copy; 2019-2025 Michał Bukowski (m.bukowski@uj.edu.pl) ZBA WBBiB UJ</span>

---

## 1. Przygotowanie środowiska

<font size=2>Korzystając z magicznej komendy `!`, utwórz komendą Bash `mkdir` katalogi `dbs` i `output`. Po prostu podaj wszystkie ścieżki/nazwy katalogów oddzielone spacjami po wpisaniu samej komendy. Możesz skorzystać z paramteru `-p`, aby uniknąć pojawiania się błędu, gdy katalogi już istnieją (np. w trakcie ponownego uruchomienia kodu całego notatnika).
</font>

In [2]:
! mkdir -p dbs output

---

## 2. BLAST: tworzenie bazy danych

#### Narzędzie _makeblastdb_ i tworzenie bazy danych z wykorzystaniem przekierowania do _stdin_

<font size=2>Wiedząc, że w powłoce tekstowej Bash:

* wyjście standardowe (<i>standard output</i>, <i>stdout</i>) domyślnie jest tym co widzisz na ekranie
* _stdout_ z jednej aplikacji można przekierować do wejścia standardowego (<i>standard input</i>, <i>stdin</i>) do innej znakiem `|`,\
np.: `app1 | app2`
* aplikacja `cat plik1.txt plik2.txt ...` kopiuje do <i>stdout</i> zawartość pliku(ów)
* nazwy wielu plików o takim samym wzorcu nazwy można zastępować wyrażeniem zastępczym (<i>wildcard</i>),\
np.: `cat *.txt`
* aby utworzyć nukleotydową bazę danych narzędziem `makeblastdb` należy podać mu przynajmniej cztery parametry: `-in` ścieżkę do pliku z sekwencjami w formacie fasta, `-dbtype` <i>nucl</i> w przypadku sekwencji nukleotydowych, `-title` własną nazwę bazy danych i `-out` ścieżkę do katalogu wraz z prefiksem nazw plików tworzonej bazy danych
* parametr `-in` przyjmuje tylko jeden plik, można go pominąć a wtedy `makeblastdb` będzie odczytywało dane ze strumienia <i>stdin</i>

i korzystając z odpowiedniej `%%magicznej komendy` wpisz i uruchom w poniższej komórce kod Bash, który aplikacją `cat` wrzuci zawartość plików `*.fna` z katalogu `genomes` do <i>stdout</i> i przekieruje je do <i>stdin</i> `makeblastdb` celem utworzenia nukleotydowej bazy danych `genomes` w katalogu `dbs`
\
\
Następnie dopisz linię `ls -l dbs`, która wyświetli zawartość katalogu `dbs`

</font>

In [3]:
%%bash
cat genomes/*.fna | makeblastdb -dbtype nucl -title "genomes" -out dbs/genomes
ls -l dbs

Building a new DB, current time: 10/23/2025 16:03:52
New DB name:   /Users/aleksanderstanuch/dev/bioinformatics/cwiczenia2/dbs/genomes
New DB title:  genomes
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 222 sequences in 0.653294 seconds.


total 13808
-rw-r--r--@ 1 aleksanderstanuch  staff    81920 Oct 23 16:03 genomes.ndb
-rw-r--r--@ 1 aleksanderstanuch  staff    43232 Oct 23 16:03 genomes.nhr
-rw-r--r--@ 1 aleksanderstanuch  staff     2756 Oct 23 16:03 genomes.nin
-rw-r--r--@ 1 aleksanderstanuch  staff      454 Oct 23 16:03 genomes.njs
-rw-r--r--@ 1 aleksanderstanuch  staff     2672 Oct 23 16:03 genomes.not
-rw-r--r--@ 1 aleksanderstanuch  staff  6857061 Oct 23 16:03 genomes.nsq
-rw-r--r--@ 1 aleksanderstanuch  staff    65536 Oct 23 16:03 genomes.ntf
-rw-r--r--@ 1 aleksanderstanuch  staff      892 Oct 23 16:03 genomes.nto

---

## 3. BLAST: przeszukiwanie bazy danych
<font size=2>Następnie w kolejnej komórce wpisz i uruchom narzędzie `blastn`, podając jako sekwencję _query_ ścieżkę do pliku `input/gap.fna`, jako bazę danych, ścieżkę do tej dopiero utworzonej, a wyniki zapisz do pliku `output/blastn.txt`. Nie zapomnij o odpowiedniej `%%magicznej komendzie`, która pozwoli Ci uruchomić zawartość całej komórki jako kod Bash.
\
\
Następnie dopisz linię `head -25 output/blast.txt`, która wyświetli pierwszych 25 linii pliku z wynikami.
\
\
Na koniec przejdź do ekranu głównego Jupytera, wejdź do katalogu `output`, otwórz i przeglądnij całą zawartość pliku `blastn.txt`.</font>

In [6]:
%%bash
blastn -query input/gap.fna -db dbs/genomes -out output/blastn.txt
head -25 output/blastn.txt

BLASTN 2.17.0+


Reference: Zheng Zhang, Scott Schwartz, Lukas Wagner, and Webb
Miller (2000), "A greedy algorithm for aligning DNA sequences", J
Comput Biol 2000; 7(1-2):203-14.



Database: genomes
           222 sequences; 27,426,152 total letters



Query= gap

Length=1011
                                                                      Score     E
Sequences producing significant alignments:                          (Bits)  Value

UDMK01000001.1 Staphylococcus aureus strain EOE252 genome assembl...  1851    0.0
UDIR01000001.1 Staphylococcus aureus strain EOE046 genome assembl...  1851    0.0
UHCG01000001.1 Staphylococcus aureus strain NCTC9553 genome assem...  1851    0.0
OGBR01000034.1 Staphylococcus aureus strain RH238 genome assembly...  1851    0.0
FQKY01000001.1 Staphylococcus argenteus strain 3688STDY6125110 ge...  1757    0.0

---

## 4. BLAST: otrzymywanie wyników w formacie tabelarycznym
<font size=2>Skpiuj kod z poprzedniej komórki i zmodyfikuj go tak, aby narzędzie `blastn` zapisało wyniki w formie tabelarycznej do pliku `output/blast.tsv` z tabulatorem jako sepratorem kolumn i z kolumnami `sseqid sstart send qcovs pident evalue`. Do jakich wartości odnoszą się te kolumny? Jeżeli nie wiesz, w terminalu tekstowym wpisz `blastn -help` i sprawdź.
\
\
Komendą `head` wyświetl tylko 5 pierwszych linii z pliku z wynikami.
\
\
Na koniec przejdź do ekranu głównego Jupytera, wejdź do katalogu `output`, otwórz i przeglądnij całą zawartość pliku `blastn.tsv`.

In [8]:
%%bash
blastn -query input/gap.fna -db dbs/genomes -out output/blast.tsv -outfmt "6 sseqid sstart send qcovs pident evalue"
head -5 output/blast.tsv

UDMK01000001.1	276652	277662	100	99.703	0.0
UDIR01000001.1	129950	128940	100	99.703	0.0
UHCG01000001.1	795488	796498	100	99.703	0.0
OGBR01000034.1	321008	322018	100	99.703	0.0
FQKY01000001.1	1106566	1105556	100	98.022	0.0

---

## 5. Polars: przetwarzanie wyników BLAST

<font size=2>Aby wykonać kolejne kroki, wykorzystaj prezentację z ostatniego wykładu jako pomoc.</font>

In [9]:
# zaimportuj moduł polars pod nazwą 'pl'
import polars as pl

In [11]:
# wczytaj wyniki z pliku output/balstn.tsv do obiektu typu DataFrame
# a następnie wyświetl tabelę
df = pl.read_csv("output/blast.tsv", separator="\t", has_header=False)
df.columns = ["sseqid", "sstart", "send", "qcovs", "pident", "evalue"]
df

shape: (10, 6)
┌────────────────┬─────────┬─────────┬───────┬────────┬────────┐
│ sseqid         ┆ sstart  ┆ send    ┆ qcovs ┆ pident ┆ evalue │
│ ---            ┆ ---     ┆ ---     ┆ ---   ┆ ---    ┆ ---    │
│ str            ┆ i64     ┆ i64     ┆ i64   ┆ f64    ┆ f64    │
╞════════════════╪═════════╪═════════╪═══════╪════════╪════════╡
│ UDMK01000001.1 ┆ 276652  ┆ 277662  ┆ 100   ┆ 99.703 ┆ 0.0    │
│ UDIR01000001.1 ┆ 129950  ┆ 128940  ┆ 100   ┆ 99.703 ┆ 0.0    │
│ UHCG01000001.1 ┆ 795488  ┆ 796498  ┆ 100   ┆ 99.703 ┆ 0.0    │
│ OGBR01000034.1 ┆ 321008  ┆ 322018  ┆ 100   ┆ 99.703 ┆ 0.0    │
│ FQKY01000001.1 ┆ 1106566 ┆ 1105556 ┆ 100   ┆ 98.022 ┆ 0.0    │
│ FQRR01000001.1 ┆ 1121207 ┆ 1120197 ┆ 100   ┆ 97.923 ┆ 0.0    │
│ AE015929.1     ┆ 553355  ┆ 554365  ┆ 100   ┆ 89.229 ┆ 0.0    │
│ FKIN01000005.1 ┆ 1151570 ┆ 1150579 ┆ 98    ┆ 86.847 ┆ 0.0    │
│ LR134263.1     ┆ 2257955 ┆ 2256964 ┆ 98    ┆ 86.231 ┆ 0.0    │
│ FMPF01000004.1 ┆ 225112  ┆ 226103  ┆ 98    ┆ 86.014 ┆ 0.0    │
└────────────────┴─────────┴─────────┴───────┴────────┴────────┘

In [12]:
# utwórz nową tabelę poprzez zachowanie z wyjściowej tabeli
# wierszy gdzie wartość kolumny qcovs wynosi 100,
# wyświetl ją
df2 = df.filter(pl.col("qcovs") == 100)
df2

shape: (7, 6)
┌────────────────┬─────────┬─────────┬───────┬────────┬────────┐
│ sseqid         ┆ sstart  ┆ send    ┆ qcovs ┆ pident ┆ evalue │
│ ---            ┆ ---     ┆ ---     ┆ ---   ┆ ---    ┆ ---    │
│ str            ┆ i64     ┆ i64     ┆ i64   ┆ f64    ┆ f64    │
╞════════════════╪═════════╪═════════╪═══════╪════════╪════════╡
│ UDMK01000001.1 ┆ 276652  ┆ 277662  ┆ 100   ┆ 99.703 ┆ 0.0    │
│ UDIR01000001.1 ┆ 129950  ┆ 128940  ┆ 100   ┆ 99.703 ┆ 0.0    │
│ UHCG01000001.1 ┆ 795488  ┆ 796498  ┆ 100   ┆ 99.703 ┆ 0.0    │
│ OGBR01000034.1 ┆ 321008  ┆ 322018  ┆ 100   ┆ 99.703 ┆ 0.0    │
│ FQKY01000001.1 ┆ 1106566 ┆ 1105556 ┆ 100   ┆ 98.022 ┆ 0.0    │
│ FQRR01000001.1 ┆ 1121207 ┆ 1120197 ┆ 100   ┆ 97.923 ┆ 0.0    │
│ AE015929.1     ┆ 553355  ┆ 554365  ┆ 100   ┆ 89.229 ┆ 0.0    │
└────────────────┴─────────┴─────────┴───────┴────────┴────────┘

In [ ]:
# zapisz tabelę z przefiltrowanymi wynikami
# do pliku output/filtered.tsv
# a następnie z ekranu głównego Jupyter Notebook
# wejdź do katalogu output i przeglądaj tak zapisane
# wyniki oraz porównaj je z zawartością pliku z
# wynikami wyjściowymi

pl.DataFrame.write_csv(df2, "output/filtered.tsv", separator="\t")

---

## 6. Polars: _DataFrame_ w trybie tekstowym

<font size=2>Uruchom terminal tekstowy, przejdź do aktualnego katalogu roboczego komendą Bash `cd ścieżka_katalogu`, uruchom tekstowy interpreter `ipython`, wczytaj tabelę z wyjściowymi wynikami z pliku `blastn.tsv` do struktury DataFrame i przeglądaj ją w trybie tekstowym.
\
\
Jeżeli nie pamiętasz ścieżki aktualnego katalogu roboczego, skorzystaj z magicznej komendy `%pwd`.</font>

[ wklej tutaj otrzymaną reprezentację tekstową DataFrame ]

┌────────────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ column_1       ┆ column_2 ┆ column_3 ┆ column_4 ┆ column_5 ┆ column_6 │
│ ---            ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str            ┆ i64      ┆ i64      ┆ i64      ┆ f64      ┆ f64      │
╞════════════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ UDMK01000001.1 ┆ 276652   ┆ 277662   ┆ 100      ┆ 99.703   ┆ 0.0      │
│ UDIR01000001.1 ┆ 129950   ┆ 128940   ┆ 100      ┆ 99.703   ┆ 0.0      │
│ UHCG01000001.1 ┆ 795488   ┆ 796498   ┆ 100      ┆ 99.703   ┆ 0.0      │
│ OGBR01000034.1 ┆ 321008   ┆ 322018   ┆ 100      ┆ 99.703   ┆ 0.0      │
│ FQKY01000001.1 ┆ 1106566  ┆ 1105556  ┆ 100      ┆ 98.022   ┆ 0.0      │
│ FQRR01000001.1 ┆ 1121207  ┆ 1120197  ┆ 100      ┆ 97.923   ┆ 0.0      │
│ AE015929.1     ┆ 553355   ┆ 554365   ┆ 100      ┆ 89.229   ┆ 0.0      │
│ FKIN01000005.1 ┆ 1151570  ┆ 1150579  ┆ 98       ┆ 86.847   ┆ 0.0      │
│ LR134263.1     ┆ 2257955  ┆ 2256964  ┆ 98       ┆ 86.231   ┆ 0.0      │
│ FMPF01000004.1 ┆ 225112   ┆ 226103   ┆ 98       ┆ 86.014   ┆ 0.0      │
└────────────────┴──────────┴──────────┴──────────┴──────────┴──────────┘